name: disk
step_size: ${target.dis.step_size}
batch_size: ${target.all.batch_size}
iters: 40000
loss: "is"  # use FB-RND
grad_clip: 1.
eval_ode: True

defaults:
  - model: pisgrad_net

model:
  bias_init: 1.0
  weight_init: 1e-8

init_std: 7.5  # prior ~ N(0, T^2 I). This should equal karras.sigma_max.
num_steps: 128

karras:
  sigma_max: ${algorithm.init_std}  # T in EDM paper
  sigma_min: 0.002  # eps in CM/EDM
  rho: 7.0

debug:
  traj_batch: 64