# configs/setup.yaml
hydra:
  run:
    dir: logs/${hydra.job.name}/runs/${slug:${hydra:overrides.task}}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${hydra.job.name}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true


wandb:
  project: single_step_diffusion_samplers
  entity: pascal_jutras_dube
  dir: ${paths.output}
  resume: allow
  mode: run
  name:
  tags: []
  id: